git push action add

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,4 +1,4 @@
-name: Build and Push Docker Image
+name: Push Docker Image and build
 
 on:
   push:
@@ -37,9 +37,45 @@ jobs:
           tags: |
             ksc036/blog-backend:${{ env.TAG }}
             ksc036/blog-backend:latest
+  gitops-update:
+    runs-on: ubuntu-latest
+    environment: git
+    needs: docker-build-and-push
+    steps:
+      - name: Checkout GitOps Repo
+        uses: actions/checkout@v3
+        with:
+          repository: ksc036/gitops-repo
+          token: ${{ secrets.GITOPS_TOKEN }}
+      - name: Set Variables from Tag
+        run: |
+          echo "GIT_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
+          if [[ "${GIT_TAG}" == dev-v* ]]; then
+            echo "ENV_DIR=dev" >> $GITHUB_ENV
+            echo "env_dir=dev" >> $GITHUB_OUTPUT
+            echo "APP_VERSION=${GIT_TAG#dev-}" >> $GITHUB_ENV
+          elif [[ "${GIT_TAG}" == prod-v* ]]; then
+            echo "ENV_DIR=prod" >> $GITHUB_ENV
+            echo "env_dir=prod" >> $GITHUB_OUTPUT
+            echo "APP_VERSION=${GIT_TAG#prod-}" >> $GITHUB_ENV
+          else
+            echo "Invalid tag format"; exit 1
+          fi
+
+      - name: Update values.yaml
+        run: |
+          sed -i "s/\(image: .*:\).*/\1${GIT_TAG}/" namespaces/${ENV_DIR}/bolg/be/deployment.yaml
+
+      - name: Commit and Push to GitOps Repo
+        run: |
+          cd gitops
+          git config user.name "github-actions"
+          git config user.email "ksc036@gmail.com"
+          git commit -am "Update ${ENV_DIR} to ${GIT_TAG}"
+          git push
   argocd-deploy:
     runs-on: ubuntu-latest
-    needs: docker-build-and-push
+    needs: gitops-update
     environment: argocd
     steps:
       - name: Install Argo CD CLI
@@ -56,5 +92,7 @@ jobs:
 
       - name: Sync application
         run: |
+          echo "ENV_DIR is ${{ needs.gitops-update.outputs.env_dir }}"
           echo "=== Current app list ==="
           argocd app list
+          argocd app sync argocd/${{ needs.gitops-update.outputs.env_dir }}-app
